#pragma once
#include "core.h"
#include "session_definition.h"
namespace pp {
class RaceEngineModule {
public:
  static constexpr uint8_t MaxEntries=2,MaxLaps=16;
  struct LapRecord{uint32_t lapNumber=0;Time startTime=0,finishTime=0,lapTime=0;bool valid=false;};
  struct EntryState{uint32_t raceEntryId=0,laps=0;Time lastCrossing=0,lastLapTime=0;bool hasLap=false;LapRecord records[MaxLaps]{};uint8_t recordCount=0;};
  struct ResultEntry{uint32_t raceEntryId=0,laps=0,rank=0,lapsBehind=0;uint8_t lane=0;bool tied=false,completed=false;Time completionTime=0,bestLap=0;LapRecord records[MaxLaps]{};uint8_t recordCount=0;};
  struct CompletedRaceResult{bool sealed=false,valid=false,deadHeat=false,fastestLapTied=false;Time winningTime=0,finishTime=0;LapFinishBehaviour behaviour=LapFinishBehaviour::Immediate;ResultEntry entries[MaxEntries]{};uint8_t entryCount=0;Time fastestLap=0;uint32_t fastestEntryId=0;};
  RaceEngineModule(Bus&b,Bus::Endpoint e,ActiveSessionDefinition&a):bus_(b),endpoint_(e),active_(a){}
  void resetForFixture(){definition_=nullptr;reset(0);} void begin(const SessionDefinition&d,Time go){definition_=&d;observedRevision_=active_.revision();reset(go);} void prepare(const SessionDefinition&d){definition_=&d;observedRevision_=active_.revision();reset(0);}
  void tick(){synchronise();Message m;while(bus_.receive(endpoint_,m)){if(m.type==Type::GoScheduled)scheduled(m);else if(m.type==Type::InputEvent)queue(m);else if(m.type==Type::SessionOperation)operation(m);else if(m.type==Type::InputSettlement){settlementSeen_=true;settlementAt_=m.relevantTime;}else if(m.type==Type::FinishSettled)finishSettled_=m.relevantTime==candidateF_;else if(m.type==Type::RaceIntegrityFault)faulted_=true;}process();publishPauseSettlement();publishFinishSettlement();completeAfterSettlement();}
  uint32_t laps()const{return entries_[0].laps;}Time lastLapTime()const{return entries_[0].lastLapTime;}bool complete()const{return complete_;}Time go()const{return go_;}uint8_t entryCount()const{return definition_?definition_->entryCount():0;}const EntryState&entryState(uint8_t i)const{return entries_[i];}bool deadHeat()const{return deadHeat_;}bool faulted()const{return faulted_;}const CompletedRaceResult&completedResult()const{return result_;}
private:
  void reset(Time go){go_=go;pauseAt_=restartAt_=settlementAt_=winningTime_=candidateF_=0;winner_=0;observedMask_=requiredMask_=0;complete_=completionPublished_=deadHeat_=faulted_=paused_=restartScheduled_=gridRestart_=false;settlementSeen_=settlementPublished_=finishReady_=finishSettlementSent_=finishSettled_=false;pendingCount_=seenAt_=0;for(auto&x:seen_)x=0;for(auto&e:entries_)e={};result_={};finishBehaviour_=definition_?definition_->finishBehaviour():LapFinishBehaviour::Immediate;if(definition_)for(uint8_t i=0;i<entryCount();++i)entries_[i].raceEntryId=definition_->entry(i).raceEntryId;}
  void synchronise(){if(active_.revision()!=observedRevision_){definition_=active_.current();observedRevision_=active_.revision();reset(0);}}
  void scheduled(const Message&m){if(definition_&&m.relevantTime){go_=m.relevantTime;for(uint8_t i=0;i<entryCount();++i)entries_[i].lastCrossing=go_;}}
  void operation(const Message&m){if(m.operation==SessionOperation::Pause){pauseAt_=m.relevantTime;paused_=true;return;}settlementSeen_=settlementPublished_=false;settlementAt_=0;restartScheduled_=true;restartAt_=m.relevantTime;gridRestart_=m.restartMethod==RestartMethod::Grid;paused_=false;if(gridRestart_)for(uint8_t i=0;i<entryCount();++i)entries_[i].lastCrossing=restartAt_;}
  void queue(const Message&m){if(!definition_||complete_||faulted_||!go_||!m.eventId||seen(m.eventId)||pendingCount_==16)return;seen_[seenAt_++%16]=m.eventId;pending_[pendingCount_++]=m;}
  bool seen(uint32_t id)const{for(auto x:seen_)if(x==id)return true;return false;}
  void process(){if(!definition_||complete_||faulted_)return;for(uint8_t i=1;i<pendingCount_;++i){Message x=pending_[i];int j=i-1;while(j>=0&&pending_[j].relevantTime>x.relevantTime){pending_[j+1]=pending_[j];--j;}pending_[j+1]=x;}for(uint8_t i=0;i<pendingCount_;++i)interpret(pending_[i]);pendingCount_=0;evaluateFinish();}
  uint8_t indexOf(uint32_t id)const{for(uint8_t i=0;i<entryCount();++i)if(entries_[i].raceEntryId==id)return i;return 0;}
  void interpret(const Message&m){if(finishReady_&&m.relevantTime>candidateF_)return;if(restartScheduled_&&m.relevantTime<restartAt_)return;SessionInputRole role;RaceEntryDefinition def;if(!definition_->resolve(m.input,role,def)||role.role!=InputRole::StartFinish)return;const uint8_t i=indexOf(def.raceEntryId);EntryState&s=entries_[i];if(m.relevantTime<=s.lastCrossing||(paused_&&m.relevantTime>=pauseAt_))return;const Time lapStart=s.lastCrossing;Time lap=m.relevantTime-lapStart;if(restartScheduled_&&!gridRestart_&&m.relevantTime>=restartAt_&&s.lastCrossing<pauseAt_){const Time stopped=restartAt_-pauseAt_;lap=lap>stopped?lap-stopped:0;}s.lastCrossing=m.relevantTime;s.lastLapTime=lap;s.hasLap=true;++s.laps;if(s.recordCount<MaxLaps){LapRecord&r=s.records[s.recordCount++];r.lapNumber=s.laps;r.startTime=lapStart;r.finishTime=m.relevantTime;r.lapTime=lap;r.valid=true;}Message f{};f.type=Type::LapCompleted;f.relevantTime=m.relevantTime;f.raceEntryId=def.raceEntryId;f.lapNumber=s.laps;f.lapTime=lap;f.eventId=m.eventId;bus_.publish(endpoint_,f);Message n{};n.type=Type::NoticeboardChanged;bus_.publish(endpoint_,n);applyFinish(i,m.relevantTime);}
  void applyFinish(uint8_t i,Time at){EntryState&s=entries_[i];const bool target=s.laps>=definition_->lapTarget();if(!winningTime_&&target){winningTime_=at;winner_=s.raceEntryId;observedMask_|=uint8_t(1u<<i);requiredMask_=uint8_t((1u<<entryCount())-1u);if(finishBehaviour_==LapFinishBehaviour::Immediate){candidateF_=at;finishReady_=true;}return;}if(!winningTime_)return;if(at==winningTime_&&target){observedMask_|=uint8_t(1u<<i);deadHeat_=true;return;}if(at<=winningTime_||(observedMask_&uint8_t(1u<<i)))return;if(finishBehaviour_==LapFinishBehaviour::CompleteCurrentLap||(finishBehaviour_==LapFinishBehaviour::CompleteFullRaceDistance&&target)){observedMask_|=uint8_t(1u<<i);candidateF_=at;if(observedMask_==requiredMask_)finishReady_=true;}}
  void evaluateFinish(){if(!winningTime_||finishReady_)return;if(finishBehaviour_==LapFinishBehaviour::Immediate){candidateF_=winningTime_;finishReady_=true;}else if(observedMask_==requiredMask_){if(candidateF_<winningTime_)candidateF_=winningTime_;finishReady_=true;}}
  void publishPauseSettlement(){if(!settlementSeen_||settlementPublished_||pendingCount_)return;Message m{};m.type=Type::PauseSettled;m.relevantTime=settlementAt_;if(bus_.publish(endpoint_,m)==Delivery::Delivered)settlementPublished_=true;}
  void publishFinishSettlement(){if(!finishReady_||finishSettlementSent_||pendingCount_)return;Message m{};m.type=Type::FinishSettlement;m.relevantTime=candidateF_;if(bus_.publish(endpoint_,m)==Delivery::Delivered)finishSettlementSent_=true;}
  void completeAfterSettlement(){if(!finishSettled_||completionPublished_||!finishSettlementSent_)return;if(!result_.sealed)seal();Message m{};m.type=Type::CompetitionComplete;m.relevantTime=result_.finishTime;m.raceEntryId=winner_;m.probe=deadHeat_?1:0;if(bus_.publish(endpoint_,m)==Delivery::Delivered){completionPublished_=true;complete_=true;}}
  static bool before(const ResultEntry&a,const ResultEntry&b,LapFinishBehaviour f){if(a.laps!=b.laps)return a.laps>b.laps;if(f==LapFinishBehaviour::Immediate)return false;if(!a.completionTime)return false;if(!b.completionTime)return true;return a.completionTime<b.completionTime;}
  static bool samePlace(const ResultEntry&a,const ResultEntry&b,LapFinishBehaviour f){return a.laps==b.laps&&(f==LapFinishBehaviour::Immediate||a.completionTime==b.completionTime);}
  void seal(){result_={};result_.sealed=true;result_.valid=!faulted_;result_.deadHeat=deadHeat_;result_.winningTime=winningTime_;result_.finishTime=candidateF_;result_.behaviour=finishBehaviour_;result_.entryCount=entryCount();uint32_t leaderLaps=0;for(uint8_t i=0;i<entryCount();++i){auto&t=result_.entries[i];const auto&s=entries_[i];t.raceEntryId=s.raceEntryId;t.lane=definition_->entry(i).lane;t.laps=s.laps;t.completed=(observedMask_&uint8_t(1u<<i))!=0;t.completionTime=t.completed?s.lastCrossing:0;t.recordCount=s.recordCount;if(t.laps>leaderLaps)leaderLaps=t.laps;for(uint8_t j=0;j<s.recordCount;++j){t.records[j]=s.records[j];if(s.records[j].valid&&(!t.bestLap||s.records[j].lapTime<t.bestLap))t.bestLap=s.records[j].lapTime;}}if(entryCount()==2&&before(result_.entries[1],result_.entries[0],finishBehaviour_)){auto t=result_.entries[0];result_.entries[0]=result_.entries[1];result_.entries[1]=t;}uint32_t rank=1;for(uint8_t i=0;i<entryCount();++i){if(i&&!samePlace(result_.entries[i-1],result_.entries[i],finishBehaviour_))rank=i+1;auto&t=result_.entries[i];t.rank=rank;t.tied=i&&result_.entries[i-1].rank==rank;if(t.tied)result_.entries[i-1].tied=true;t.lapsBehind=leaderLaps-t.laps;for(uint8_t j=0;j<t.recordCount;++j){const auto&lap=t.records[j];if(!lap.valid)continue;if(!result_.fastestLap||lap.lapTime<result_.fastestLap){result_.fastestLap=lap.lapTime;result_.fastestEntryId=t.raceEntryId;result_.fastestLapTied=false;}else if(lap.lapTime==result_.fastestLap&&result_.fastestEntryId!=t.raceEntryId)result_.fastestLapTied=true;}}}
  Bus&bus_;Bus::Endpoint endpoint_;ActiveSessionDefinition&active_;const SessionDefinition*definition_=nullptr;uint32_t observedRevision_=0;Time go_=0,pauseAt_=0,restartAt_=0,settlementAt_=0,winningTime_=0,candidateF_=0;EntryState entries_[MaxEntries]{};LapFinishBehaviour finishBehaviour_=LapFinishBehaviour::Immediate;uint8_t observedMask_=0,requiredMask_=0;bool complete_=false,completionPublished_=false,deadHeat_=false,faulted_=false,paused_=false,restartScheduled_=false,gridRestart_=false,settlementSeen_=false,settlementPublished_=false,finishReady_=false,finishSettlementSent_=false,finishSettled_=false;CompletedRaceResult result_{};uint32_t winner_=0;Message pending_[16]{};uint8_t pendingCount_=0;uint32_t seen_[16]{};uint8_t seenAt_=0;
};
} // namespace pp
