[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = default.csv
build_flags = -Wall -Wextra

[env:verification]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DPP_VERIFY=1

[env:quiet]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DPP_DIAGNOSTICS=0

[env:acceptance]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DPP_ACCEPTANCE=1
