const fs = require('fs');
const vm = require('vm');
const header = fs.readFileSync('firmware/include/pp/browser_interface.h','utf8');
const html = header.match(/static const char html\[\] = R"HTML\(([\s\S]*?)\)HTML";/)[1];
const baseScript = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const authority = header.match(/static const char authorityPresentation\[\] = R"HTML\(([\s\S]*?)\)HTML";/)[1].replace(/^<script>/,'').replace(/<\/script>$/,'');
class Element { constructor(id){this.id=id;this.textContent='';this.disabled=false;this.hidden=false;this.value='';this._onclick=null;this.onclickAssignments=0;} set onclick(v){this._onclick=v;this.onclickAssignments++;} get onclick(){return this._onclick;} dispatchEvent(e){return e&&e.type==='click'&&this._onclick?this._onclick(e):undefined;} before(){} set innerHTML(v){for(const m of String(v).matchAll(/id=["']([^"']+)["']/g)){if(!document.elements[m[1]])document.elements[m[1]]=new Element(m[1]);}} }
const ids=['connection','role','human','request','state','fact','bootstrap','start','pause','honour','grid','raceAgain','target3','lane1','lane2','resetTest','results','details','history','back','home','endRace','restartRace','resultView'];
global.document={elements:{},querySelector(s){return this.elements[s.replace(/^#/,'')]||null;},createElement(){return new Element('generated');}};for(const id of ids)document.elements[id]=new Element(id);global.window=global;global.$=s=>document.querySelector(s);global.performance={now:()=>Date.now()};global.setInterval=()=>1;global.clearInterval=()=>{};
let proposal={proposalRevision:1,startable:true,readiness:'READY',mode:'ENDURANCE',lapTarget:2,durationMinutes:1,finishBehaviour:'COMPLETE_CURRENT_LAP',activeLanes:2,supportedModes:[{mode:'LAP_RACE',available:true},{mode:'OPEN_PRACTICE',available:true},{mode:'ENDURANCE',available:true},{mode:'TIMED_STAGE',available:false},{mode:'DRAG',available:false}]};let state={lifecycle:'READY',sessionMode:'NONE',entries:[{lane:1,laps:0},{lane:2,laps:0}]};let stale=[];const setupRequests=[];const starts=[];
function response(v,status=200){return{ok:status>=200&&status<300,status,async json(){return JSON.parse(JSON.stringify(v));}}}
global.fetch=async(path,opt={})=>{if(path==='/noticeboard')return response({revision:1,proposalRevision:proposal.proposalRevision});if(path==='/context')return response({hasMaster:true,role:'Race Director'});if(path==='/state')return response(stale.length?stale.shift():state);if(path==='/proposal')return response(proposal);if(path==='/fact')return response({type:'NONE',revision:0});if(path==='/request/setup'){const b=JSON.parse(opt.body);setupRequests.push(b);if(b.proposalRevision!==proposal.proposalRevision)return response({submitted:false,reason:'PROPOSAL_REVISION_CONFLICT'},409);proposal={...proposal,mode:b.mode,lapTarget:b.lapTarget,durationMinutes:b.durationMinutes,finishBehaviour:b.finishPolicy===1?'COMPLETE_CURRENT_LAP':'IMMEDIATE',proposalRevision:proposal.proposalRevision+1};return response({submitted:true,correlationId:b.correlationId},202);}if(path==='/request/start'){const b=JSON.parse(opt.body);starts.push(b);state={lifecycle:'RACING',sessionMode:proposal.mode,entries:[{lane:1,laps:0},{lane:2,laps:0}]};proposal={...proposal,startable:false};return response({submitted:true,correlationId:b.correlationId},202);}if(path.startsWith('/request-result'))return response({result:'ACCEPTED',reason:'NONE'});if(path==='/fixture')return response({},200);return response({},200);};
vm.runInThisContext(baseScript,{filename:'browser-html.js'});vm.runInThisContext(authority,{filename:'authority-presentation.js'});
async function poll(){await window.poll();}
function expect(v,m){if(!v)throw new Error(m);}
(async()=>{await new Promise(r=>setTimeout(r,1));await poll();const initial=await (await fetch('/proposal')).json();expect(initial.startable&&initial.mode==='ENDURANCE'&&initial.supportedModes.some(x=>x.mode==='LAP_RACE'&&x.available)&&initial.supportedModes.some(x=>x.mode==='OPEN_PRACTICE'&&x.available)&&initial.supportedModes.some(x=>x.mode==='ENDURANCE'&&x.available)&&initial.supportedModes.some(x=>x.mode==='TIMED_STAGE'&&!x.available)&&initial.supportedModes.some(x=>x.mode==='DRAG'&&!x.available),'authoritative proposal/readiness/capabilities were not reconstructed');expect(document.elements.selectEndurance.textContent==='ENDURANCE SELECTED','initial proposal was not reconstructed');document.elements.selectPractice.dispatchEvent({type:'click'});await poll();expect(proposal.mode==='OPEN_PRACTICE'&&document.elements.selectPractice.textContent==='OPEN PRACTICE SELECTED'&&document.elements.selectEndurance.textContent==='SELECT ENDURANCE','setup boundary did not make modes exclusive');const staleRevision=setupRequests[0].proposalRevision;const staleResponse=await fetch('/request/setup',{method:'POST',body:JSON.stringify({correlationId:9901,mode:'ENDURANCE',lapTarget:2,durationMinutes:1,finishPolicy:0,proposalRevision:staleRevision})});expect(staleResponse.status===409&&proposal.mode==='OPEN_PRACTICE','second stale client was not rejected without changing the accepted proposal');for(let i=0;i<20;i++){stale.push({lifecycle:'RACING',sessionMode:'ENDURANCE',entries:[]});await poll();expect(document.elements.selectPractice.textContent==='OPEN PRACTICE SELECTED'&&document.elements.selectEndurance.textContent==='SELECT ENDURANCE','stale active state changed proposal');}document.elements.start.dispatchEvent({type:'click'});await poll();expect(starts.length===1&&Object.keys(starts[0]).length===1&&state.sessionMode==='OPEN_PRACTICE','generic START did not commit current P&P proposal');state={lifecycle:'READY',sessionMode:'NONE',entries:[]};proposal={...proposal,startable:true,mode:'OPEN_PRACTICE',proposalRevision:proposal.proposalRevision+1};await poll();document.elements.selectEndurance.dispatchEvent({type:'click'});await poll();expect(proposal.mode==='ENDURANCE'&&document.elements.selectEndurance.textContent==='ENDURANCE SELECTED'&&document.elements.selectPractice.textContent==='SELECT OPEN PRACTICE','reverse setup was not exclusive');console.log('Stage 14C Browser authority runtime PASS: production proposal polling, setup boundary, stale-client rejection, stale-state isolation, capabilities and generic START');})().catch(e=>{console.error('Stage 14C Browser authority runtime FAIL:',e.stack||e.message);process.exitCode=1;});
